# Generated by Django 4.1 on 2022-08-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinpages', '0002_alter_income_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='notes_text',
            field=models.TextField(default='--'),
        ),
        migrations.AlterField(
            model_name='income',
            name='notes',
            field=models.CharField(default='--', max_length=64),
        ),
    ]
