# Generated by Django 4.1 on 2022-08-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfinpages', '0003_income_notes_text_alter_income_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='notes_text',
        ),
    ]
