# Generated by Django 4.1 on 2022-08-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinpages', '0004_remove_income_notes_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='comment_to_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
