# Generated by Django 4.1 on 2022-08-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinpages', '0008_alter_income_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='comment_to_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='notes',
            field=models.CharField(default='---', max_length=64),
        ),
        migrations.AlterField(
            model_name='income',
            name='notes',
            field=models.CharField(default='---', max_length=255),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='notes',
            field=models.CharField(default='---', max_length=64),
        ),
    ]
