# Generated by Django 4.1 on 2022-10-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myfinpages", "0010_alter_balance_type_alter_income_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balance",
            name="comment_to_notes",
        ),
        migrations.RemoveField(
            model_name="income",
            name="comment_to_notes",
        ),
        migrations.RemoveField(
            model_name="outcome",
            name="comment_to_notes",
        ),
    ]
