# Generated by Django 4.1 on 2022-10-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myfinpages", "0011_remove_balance_comment_to_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="comment_to_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="income",
            name="comment_to_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outcome",
            name="comment_to_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
