# Generated by Django 4.1 on 2022-10-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "myfinpages",
            "0012_balance_comment_to_notes_income_comment_to_notes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "SALARY"),
                    (2, "BONUS"),
                    (3, "OTHER"),
                    (4, "SAVINGS"),
                    (5, "GIFT"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="outcome",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "BILLS"),
                    (2, "GROCERIES"),
                    (3, "CLOTHES"),
                    (4, "STUDY"),
                    (5, "SPORT"),
                    (6, "FUN"),
                    (7, "HEALTH"),
                    (8, "HOME"),
                    (9, "FAMILY"),
                    (10, "GIFT"),
                    (11, "OTHER"),
                    (12, "SAVINGS"),
                    (13, "TRAVEL"),
                ],
                default=1,
            ),
        ),
    ]
